In [70]:
import pandas as pd


#딕셔너리
#키=열
#값=행

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Score': [85, 90, 95, 80, 70]
}
df = pd.DataFrame(data)
df

      Name  Age         City  Score
0    Alice   25     New York     85
1      Bob   30  Los Angeles     90
2  Charlie   35      Chicago     95
3    David   40      Houston     80
4      Eve   45      Phoenix     70

In [71]:
#df.loc[행,열]: 이름이용 추출
#df.iloc[행,열]:순서 추출.
#1. 슬라이싱: 리스트[시작수:끝 수 :점프간격크기]
#2. []로 열(행)을 2개 이상 묶을 수 있음

In [72]:
# 문제 1 loc를 사용하여 'Name' 열과 'City' 열만 선택하세요.
# 문제 2 iloc를 사용하여 첫 번째와 세 번째 열을 선택하세요.
# 문제 3 'Age'가 30 이상인 행들을 선택하세요.
# 문제 4 iloc를 사용하여 첫 번째, 세 번째, 다섯 번째 행을 선택하세요.
# 문제 5 'Name'이 'David'인 행을 선택하세요.
# 문제 6 iloc를 사용하여 첫 번째 행의 값을 모두 선택하세요.
# 문제 7 loc를 사용하여 'Name'과 'Score' 열을 선택하고, 'Score'가 80보다 큰 행을 선택하세요.
# 문제 8 iloc를 사용하여 두 번째와 네 번째 열의 값을 선택하세요.
# 문제 9 loc를 사용하여 'Eve'의 나이를 50으로 변경하세요.
# 문제 10 iloc를 사용하여 첫 번째 행 네 번째 열의 값을 75로 변경하세요.

9,10번 변경 예약어 기억 안남.. replace? 아님 함수 적용인가?

In [73]:
# 문제 1 loc를 사용하여 'Name' 열과 'City' 열만 선택하세요.

df.loc[:,['Name','City']]

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston
4      Eve      Phoenix

In [74]:
# 문제 2 iloc를 사용하여 첫 번째와 세 번째 열을 선택하세요.
df.iloc[:,[0,2]]

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston
4      Eve      Phoenix

In [75]:
# 문제 3 'Age'가 30 이상인 행들을 선택하세요.
#df[조건]
#df[df['Age'] >=30]도 가능
df.loc[df['Age']>=30]

      Name  Age         City  Score
1      Bob   30  Los Angeles     90
2  Charlie   35      Chicago     95
3    David   40      Houston     80
4      Eve   45      Phoenix     70

In [76]:
# 문제 4 iloc를 사용하여 첫 번째, 세 번째, 다섯 번째 행을 선택하세요.

#df.iloc[[0,2,4],:]
df.iloc[[0,2,4]]

      Name  Age      City  Score
0    Alice   25  New York     85
2  Charlie   35   Chicago     95
4      Eve   45   Phoenix     70

In [77]:
# 문제 5 'Name'이 'David'인 행을 선택하세요.

df[df['Name']=='David']
#df.loc[df['Name']=='David']

    Name  Age     City  Score
3  David   40  Houston     80

In [78]:
# 문제 6 iloc를 사용하여 첫 번째 행의 값을 모두 선택하세요.
df.iloc[[0]]
#df.iloc[0,:]

    Name  Age      City  Score
0  Alice   25  New York     85

In [79]:
# 문제 7 loc를 사용하여 'Name'과 'Score' 열을 선택하고, 'Score'가 80보다 큰 행을 선택하세요.
df.loc[df['Score']>=80, ['Name','Score']]

      Name  Score
0    Alice     85
1      Bob     90
2  Charlie     95
3    David     80

In [80]:
# 문제 8 iloc를 사용하여 두 번째와 네 번째 열의 값을 선택하세요.

df.iloc[:,[1,3]]

   Age  Score
0   25     85
1   30     90
2   35     95
3   40     80
4   45     70

In [81]:
#데이터 프레임에서 '변경': = 활용
df['Score'] = [100, 40, 50, 70, 80]
df

      Name  Age         City  Score
0    Alice   25     New York    100
1      Bob   30  Los Angeles     40
2  Charlie   35      Chicago     50
3    David   40      Houston     70
4      Eve   45      Phoenix     80

In [86]:
# 문제 9 loc를 사용하여 'Eve'의 나이를 50으로 변경하세요.

#1 조건: eve 찾기
df.loc [df['Name']=='Eve', 'Age'] = 50

df


#replace 활용해서 해봐

#df.loc [df['Name']=='Eve', 'Age']

      Name  Age         City  Score   age
0    Alice   25     New York    100   NaN
1      Bob   30  Los Angeles     40   NaN
2  Charlie   35      Chicago     50   NaN
3    David   40      Houston     70   NaN
4      Eve   50      Phoenix     80  50.0

In [92]:
# 문제 10 iloc를 사용하여 첫 번째 행 네 번째 열의 값을 75로 변경하세요.
df.iloc[0,3] = 75
df

#조건: 0,3. replace 사용
    # df.iloc[df:[0,3]]

      Name  Age         City  Score   age
0    Alice   25     New York     75   NaN
1      Bob   30  Los Angeles     40   NaN
2  Charlie   35      Chicago     50   NaN
3    David   40      Houston     70   NaN
4      Eve   50      Phoenix     80  50.0