#1. 복습
- 판다스

In [ ]:
#pandas: 행과 열 데이터를 라이브러리
#설치 명령어
#차이: '!'. 코랩은 프로그램, '터미널에서' 라는 뜻을 가짐.
!pip install pandas matplotlib seaborn

#기존 라이브러리 제거: !pip uninstall pandas

#버전 지정
#!pip install pandas=2.0

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
#판다스 임포트

import pandas as pd

In [ ]:
#자료형: Series (한 줄), DataFrame(행열)


#생성방법: 딕셔너리 형태로 df 생성

data1= {"a" : [1, 2, 3, 4],
        "b" : [2, 4, 6, 8],
        "c" : [1, 3, 5, 7]}

#이중 리스트로 df 만들기.

data2 = [[100, 1, 10],
        [350, 7, 15],
        [250, 5, 5],
        [550, 14, 0]]


df = pd.DataFrame(data1)
df

   a  b  c
0  1  2  1
1  2  4  3
2  3  6  5
3  4  8  7

In [ ]:
#전치(Transpose): , T(가로-세로, 행-열 바꿈)
df = df.T
print(df)

   0  1  2  3
a  1  2  3  4
b  2  4  6  8
c  1  3  5  7

In [ ]:
#컬럼(columns): 열 이름
#인덱스(index): 행 이름

print(df.columns, df.index)

RangeIndex(start=0, stop=4, step=1) Index(['a', 'b', 'c'], dtype='object')

In [ ]:
df.columns = [ '1st', '2nd', '3rd', '4th']
print(df)

   1st  2nd  3rd  4th
a    1    2    3    4
b    2    4    6    8
c    1    3    5    7

In [ ]:
#pd.DataFrame(x, ): x는 데이터, 콤마 뒤 옵션 가능
    #index
    #columns
df = pd.DataFrame(data1,
                  index =['1st', '2nd', '3rd', '4th'] ,
                  columns =['a', 'b', 'c'])
print(df)

     a  b  c
1st  1  2  1
2nd  2  4  3
3rd  3  6  5
4th  4  8  7

In [ ]:
#pandas documentation: 다운 받아서 오프라인 활용 가능. AI나 서칭 불가한 환경에서 사용토록. 판다스 관련한 명령어, 판다스 가이드 격.

In [ ]:
#각 위에서 5줄, 아래에서 5줄 출력.
#head(N): 데이터 프레임의 가장 위 N줄을 불러옴. 디폴트는 5줄. tail도 동일.

#head
print(df.head())


#tail
print(df.tail())

     a  b  c
1st  1  2  1
2nd  2  4  3
3rd  3  6  5
4th  4  8  7
     a  b  c
1st  1  2  1
2nd  2  4  3
3rd  3  6  5
4th  4  8  7

## 2. 데이터의 행열에 접근

 - loc: 컬럼과 인덱스의 이름
 - iloc: 컬럼과 인덱스의 순서

In [ ]:
df

     a  b  c
1st  1  2  1
2nd  2  4  3
3rd  3  6  5
4th  4  8  7

In [ ]:
#df.loc[행조건,열조건]
#'한 칸' -> np.int64(1) np.int64 (자료형), 1 (값) -> int(1)
df.loc['1st', 'a']       #결과로 np.int64 나와야함.

np.int64(1)

In [ ]:
df.loc['1st', 'a':'b']          #행열은 뒤집히지 않음. 그대로이지만 코랩이라 표기가 이렇게 나옴

a    1
b    2
Name: 1st, dtype: int64

In [ ]:
df

     a  b  c
1st  1  2  1
2nd  2  4  3
3rd  3  6  5
4th  4  8  7

In [ ]:
df.iloc [0,1]  #파이썬 순서

np.int64(2)

In [ ]:
#df를 새로 덮어쓰는 것. 위의 내용들이 에러가 날 것. (기본적으로 전체 실행은 선형이지만 내가 개별로 실행하게되면 오류 가능)
#df = pd.DataFrame(data2)

df2 = pd.DataFrame(data2)

In [ ]:
df2

     0   1   2
0  100   1  10
1  350   7  15
2  250   5   5
3  550  14   0

In [ ]:
df2.index = ['1호점', '2호점', '3호점', '4호점']
df2.columns = ['매출액', '점원수', '점포비용']

df2

     매출액  점원수  점포비용
1호점  100    1    10
2호점  350    7    15
3호점  250    5     5
4호점  550   14     0

In [ ]:
#데이터 추출 다른 방법: df2[[,]]           [ 조건[행,열] ] 꼴
#데이터프레임의 '조건'을 갖고 추출할 때 []로 묶는 것
df2[['매출액','점포비용']]


#df2[ [df2['']==][['매출액','점포비용']] ]      수정필요
#데이터 프레임의 특정한 것이 무엇일때 ~ 라는 뜻

     매출액  점포비용
1호점  100    10
2호점  350    15
3호점  250     5
4호점  550     0

In [ ]:
#연습문제(loc, iloc 활용)

#꿀팁: print()는 한 셀에 여러 문제를 동시에 출력해줌. print() 없이 출력하면 가장 최근의 결과값 1개만 도출함

#연속된 행(2~3호점)의 특정 열[점포 비용] 불러오기

df2.loc['2호점':'3호점', ['점포비용']]

     점포비용
2호점    15
3호점     5

In [ ]:
#3호점의 점원수 불러오기

df2.loc['3호점', ['점원수']]

print(df2.loc['3호점', ['점원수']])

점원수    5
Name: 3호점, dtype: int64

In [ ]:
#1호점의 매출액 불러오기

df2.loc['1호점', ['매출액']]

print(df2.loc['1호점', ['매출액']])

매출액    100
Name: 1호점, dtype: int64

In [ ]:
#2,3호점의 매출액과 점포비용 불러오기

df2.loc['2호점':'3호점', ['매출액', '점포비용']]

print(df2.loc['2호점':'3호점', ['매출액', '점포비용']])

     매출액  점포비용
2호점  350    15
3호점  250     5

In [ ]:
#선생님 풀이
# : > iloc에 사용 연속되어 있는 숫자일 때 사용하는 것이 좋음. 문자로 된 경우는 지양
# , > loc에 사용
print(df2.loc[['2호점','3호점'], ['매출액', '점포비용']])

     매출액  점포비용
2호점  350    15
3호점  250     5

In [ ]:
df2

     매출액  점원수  점포비용
1호점  100    1    10
2호점  350    7    15
3호점  250    5     5
4호점  550   14     0

In [ ]:
#iloc 연습문제

#3호점의 점원수 불러오기

print(df2.iloc[2,1])

5

In [ ]:
#1호점의 매출액 불러오기
print(df2.iloc[0,0])

100

In [ ]:
#2,3호점의 매출액과 점포비용 불러오기

df2.iloc[1:2, [0,2]]

print(df2.iloc[1:3, [0,2]])

#loc 와의 차이점: 행 조건에 []묶음이 없다? 전체적으로 loc은 표 형태로 값을 출력해주는데 iloc은 단일한 결과일 경우 해당 위치의 값만 출력해주는 경우도 있음. 물론 다중일 경우,,,?3번일 경우 표 형태로 출력해주긴 함
#print(df2.loc[['2호점','3호점'], ['매출액', '점포비용']])


#loc 와의 차이점: 행 조건에 []묶음이 없다?
#데프.loc[[행],[열]]
#데프.iloc[행,[열]]: iloc은 숫자. 슬라이싱 가능
    #예제 행의 위치: 슬라이싱, 슬라이싱은 묶지 않음.

#차이점은
#글자와 숫자의 차이! 숫자의 슬라이싱은 뭐다? 파이썬의 순서 즉, 0부터 시작.
#똑같이 쓰더라도 글자는 '포함', 숫자는 '미만'

     매출액  점포비용
2호점  350    15
3호점  250     5

#외부 데이터 로드해 조건 주기

In [ ]:
#파이썬에서 미디어(txt, csv,jpg,...) '경로(path = )' 사용함


#구글 드라이브 마운트
#냅다 업로드 > easy!

In [ ]:
#1. 업로드 (코랩 한정 업로드 즉, 코랩 닫으면 사라짐.) >가벼운 파일에 적합함.
path = '/content/fraud_train.csv'

#read_csv(경로): path 변수 지정 안하고 주소 기입 가능하지만 편의성 고려
fraud = pd.read_csv(path)

In [ ]:
#Head 이용 5줄 출력
#print(df.head())
fraud.head()

,ip,app,device,os,channel,click_time,attributed_time,is_attributed
0,87540,12,1,13,497,2017-11-07 09:30:38,NaN,0
1,105560,25,1,17,259,2017-11-07 13:40:27,NaN,0
2,101424,12,1,19,212,2017-11-07 18:05:24,NaN,0
3,94584,13,1,13,477,2017-11-07 04:58:08,NaN,0
4,68413,12,1,1,178,2017-11-09 09:00:09,NaN,0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#2. 구글 드라이브 마운트(저장 장치를 컴퓨터에 연결하는 것)
#    -1. 아이콘을 눌러서 마운트
#    -2. 소스 코드로 마운트

#    -1. 아이콘을 눌러서 마운트
#path 지정, 변수 지정 = pd.read_csv

import pandas as pd
path = '/content/drive/MyDrive/SeSAC/fraud_train.csv'
temp = pd.read_csv(path)

temp

,ip,app,device,os,channel,click_time,attributed_time,is_attributed
0,87540,12,1,13,497,2017-11-07 09:30:38,NaN,0
1,105560,25,1,17,259,2017-11-07 13:40:27,NaN,0
2,101424,12,1,19,212,2017-11-07 18:05:24,NaN,0
3,94584,13,1,13,477,2017-11-07 04:58:08,NaN,0
4,68413,12,1,1,178,2017-11-09 09:00:09,NaN,0
...,...,...,...,...,...,...,...,...
99995,124883,11,1,19,122,2017-11-09 13:25:41,NaN,0
99996,85150,9,1,13,244,2017-11-07 11:25:43,NaN,0
99997,18839,3,1,13,19,2017-11-08 11:38:42,NaN,0
99998,114276,15,1,12,245,2017-11-08 17:55:21,NaN,0
99999,119349,14,1,15,401,2017-11-07 14:32:27,NaN,0

In [ ]:
#    -2. 소스 코드로 마운트 (1과 결과 동일)
# from google.colab import drive
# drive.mount('/content/drive')         #절대경로, 상대경로 찾으시오

#2. 데이터 분석 기초

- EDA: 탐색적 데이터 분석
    - 1. 데이터 정보 확인 (일반 통계)
    - 2. 통계정보 확인 (기술 통계) 여기까지 판다스 이용
    - 3. 시각화  여기부터는 맷플로립, 씨본 이용

- 1) 일반 정보 확인
    - 행, 열에 무엇이 있는지?
    - 데이터 길이가 얼마인지? 확인

In [ ]:
#행, 열 확인
#데이터 분석, 머신러닝 -> 데이터 규모가 만 개 정도 되면 실제 서비스 가능
# 그 이하면 성능이 조금 저하될 수 있음

print(f'열 이름 정보 : {fraud.columns}\n')
print(f'행 이름 정보 : {fraud.index}')

열 이름 정보 : Index(['ip', 'app', 'device', 'os', 'channel', 'click_time', 'attributed_time',
       'is_attributed'],
      dtype='object')

행 이름 정보 : RangeIndex(start=0, stop=100000, step=1)

In [ ]:
#데이터 길이 확인
print (len(fraud))

100000

In [ ]:
#일반 정보를 확인fraud.info(): 열의 이름, 빈 값 개수, 데이터 자료형
fraud.info()


# <class 'pandas.core.frame.DataFrame'>                     : 위치, 정보
# RangeIndex: 100000 entries, 0 to 99999                    : 행
# Data columns (total 8 columns):                           : 어떤 컬럼이 있는지
#  #   Column           Non-Null Count   Dtype              non-null count: 안 비어있는 갯수
# ---  ------           --------------   -----              Dtype: 데이터 타입 int 64(정수 64비트). object(int float 아닌 것은 무조건 이렇게 표기)
#  0   ip               100000 non-null  int64
#  1   app              100000 non-null  int64
#  2   device           100000 non-null  int64
#  3   os               100000 non-null  int64
#  4   channel          100000 non-null  int64
#  5   click_time       100000 non-null  object
#  6   attributed_time  227 non-null     object
#  7   is_attributed    100000 non-null  int64
# dtypes: int64(6), object(2)
# memory usage: 6.1+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ip               100000 non-null  int64
 1   app              100000 non-null  int64
 2   device           100000 non-null  int64
 3   os               100000 non-null  int64
 4   channel          100000 non-null  int64
 5   click_time       100000 non-null  object
 6   attributed_time  227 non-null     object
 7   is_attributed    100000 non-null  int64
dtypes: int64(6), object(2)
memory usage: 6.1+ MB

In [ ]:
#계산 통계

fraud.describe()


# 갯수, 평균, 표준편차, 최소, 1q, 2q, 3q, 최대
# 숫자가 아닌 행은 빼고 계산합니다

,ip,app,device,os,channel,is_attributed
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000
mean,91255.879670,12.04788,21.771250,22.818280,268.832460,0.002270
std,69835.553661,14.94150,259.667767,55.943136,129.724248,0.047591
min,9.000000,1.00000,0.000000,0.000000,3.000000,0.000000
25%,40552.000000,3.00000,1.000000,13.000000,145.000000,0.000000
50%,79827.000000,12.00000,1.000000,18.000000,258.000000,0.000000
75%,118252.000000,15.00000,1.000000,19.000000,379.000000,0.000000
max,364757.000000,551.00000,3867.000000,866.000000,498.000000,1.000000

##3. 데이터 조건 검색

In [ ]:
print(fraud)

           ip  app  device  os  channel           click_time attributed_time  \
0       87540   12       1  13      497  2017-11-07 09:30:38             NaN
1      105560   25       1  17      259  2017-11-07 13:40:27             NaN
2      101424   12       1  19      212  2017-11-07 18:05:24             NaN
3       94584   13       1  13      477  2017-11-07 04:58:08             NaN
4       68413   12       1   1      178  2017-11-09 09:00:09             NaN
...       ...  ...     ...  ..      ...                  ...             ...
99995  124883   11       1  19      122  2017-11-09 13:25:41             NaN
99996   85150    9       1  13      244  2017-11-07 11:25:43             NaN
99997   18839    3       1  13       19  2017-11-08 11:38:42             NaN
99998  114276   15       1  12      245  2017-11-08 17:55:21             NaN
99999  119349   14       1  15      401  2017-11-07 14:32:27             NaN

       is_attributed
0                  0
1                  0
2                  0
3                  0
4                  0
...              ...
99995              0
99996              0
99997              0
99998              0
99999              0

[100000 rows x 8 columns]

In [ ]:
#특정 열에 조건 걸기: 데이터프레임['조건']
#fraud['os']>10 True/False 로 갈리는 조건
fraud[fraud['os']>10]

,ip,app,device,os,channel,click_time,attributed_time,is_attributed
0,87540,12,1,13,497,2017-11-07 09:30:38,NaN,0
1,105560,25,1,17,259,2017-11-07 13:40:27,NaN,0
2,101424,12,1,19,212,2017-11-07 18:05:24,NaN,0
3,94584,13,1,13,477,2017-11-07 04:58:08,NaN,0
5,93663,3,1,17,115,2017-11-09 01:22:13,NaN,0
...,...,...,...,...,...,...,...,...
99995,124883,11,1,19,122,2017-11-09 13:25:41,NaN,0
99996,85150,9,1,13,244,2017-11-07 11:25:43,NaN,0
99997,18839,3,1,13,19,2017-11-08 11:38:42,NaN,0
99998,114276,15,1,12,245,2017-11-08 17:55:21,NaN,0
99999,119349,14,1,15,401,2017-11-07 14:32:27,NaN,0

In [ ]:
#ip가 10000 이하인 행만 추출

print(fraud[fraud['ip']<=10000])

         ip  app  device  os  channel           click_time attributed_time  \
16     5314    2       1   2      477  2017-11-09 07:33:41             NaN
23     8362    7       1  19      101  2017-11-07 10:30:00             NaN
52     4019   12       1  19      265  2017-11-09 01:10:59             NaN
59     3488    3       1  22      115  2017-11-07 00:12:44             NaN
63     9073    3       1  37      466  2017-11-08 04:55:00             NaN
...     ...  ...     ...  ..      ...                  ...             ...
99946  5348    1       1  53      125  2017-11-07 06:53:37             NaN
99952  4948   26       1  18      121  2017-11-07 01:15:30             NaN
99976  6908   14       1  18      123  2017-11-07 22:59:12             NaN
99977  5788   18       1  58      439  2017-11-09 14:22:21             NaN
99982  5314   12       1  41      259  2017-11-09 02:09:20             NaN

       is_attributed
16                 0
23                 0
52                 0
59                 0
63                 0
...              ...
99946              0
99952              0
99976              0
99977              0
99982              0

[7681 rows x 8 columns]

In [ ]:
#app이 홀수인 행만 추출

print(fraud[fraud['app']%2==1])

           ip  app  device  os  channel           click_time attributed_time  \
1      105560   25       1  17      259  2017-11-07 13:40:27             NaN
3       94584   13       1  13      477  2017-11-07 04:58:08             NaN
5       93663    3       1  17      115  2017-11-09 01:22:13             NaN
6       17059    1       1  17      135  2017-11-09 01:17:58             NaN
7      121505    9       1  25      442  2017-11-07 10:01:53             NaN
...       ...  ...     ...  ..      ...                  ...             ...
99994  147153   13       1  13      477  2017-11-07 07:34:13             NaN
99995  124883   11       1  19      122  2017-11-09 13:25:41             NaN
99996   85150    9       1  13      244  2017-11-07 11:25:43             NaN
99997   18839    3       1  13       19  2017-11-08 11:38:42             NaN
99998  114276   15       1  12      245  2017-11-08 17:55:21             NaN

       is_attributed
1                  0
3                  0
5                  0
6                  0
7                  0
...              ...
99994              0
99995              0
99996              0
99997              0
99998              0

[51288 rows x 8 columns]

In [ ]:
#정렬
#데이터프레임.sort_values(기준,옵션) : 특정 데이터 열을 기준으로 정렬. 옵션은 오름차순= True/False
#기준은 여러 개 설정 가능 ([기준1,기준2], 옵션) 꼴
temp1
temp1 = fraud.sort_values(['os','channel'],ascending=True)

#데이터 프레임의 인덱스 리셋: temp1.reset_index() 이렇게만 하면 인덱스가 추가된 열이 나옴,
temp1 = temp1.reset_index()


#원치 않는 열 제거: drop(columns=['index']) 이는 이 셀에만 유효하게 작용함.
#temp1.drop(columns=['index'])
#왜? drop은 임시로 설정하는 값이며 영구적으로 원하면 원본에 저장하는 것. 이는 옵션으로 작성 (~,inplace=True)
#drop은 변수에 정의하는 형태로 저장하지 않음!
temp1.drop(columns=['index'],inplace=True)


temp1

,ip,app,device,os,channel,click_time,attributed_time,is_attributed
0,347833,163,0,0,4,2017-11-09 12:28:14,NaN,0
1,103236,49,124,0,101,2017-11-09 09:16:18,NaN,0
2,278545,104,0,0,101,2017-11-09 11:21:31,NaN,0
3,7435,125,0,0,110,2017-11-08 11:24:09,NaN,0
4,5314,125,0,0,110,2017-11-08 12:48:34,NaN,0
...,...,...,...,...,...,...,...,...
99995,75848,65,3866,866,469,2017-11-09 01:23:57,NaN,0
99996,77523,65,3866,866,469,2017-11-09 10:26:27,NaN,0
99997,202344,65,3866,866,469,2017-11-09 13:08:40,NaN,0
99998,98534,65,3866,866,469,2017-11-09 11:47:48,NaN,0
99999,35643,66,3866,866,474,2017-11-09 12:40:59,NaN,0

In [ ]:
temp1#(위 drop 옵션 사례 확인용)

,ip,app,device,os,channel,click_time,attributed_time,is_attributed
0,347833,163,0,0,4,2017-11-09 12:28:14,NaN,0
1,103236,49,124,0,101,2017-11-09 09:16:18,NaN,0
2,278545,104,0,0,101,2017-11-09 11:21:31,NaN,0
3,7435,125,0,0,110,2017-11-08 11:24:09,NaN,0
4,5314,125,0,0,110,2017-11-08 12:48:34,NaN,0
...,...,...,...,...,...,...,...,...
99995,75848,65,3866,866,469,2017-11-09 01:23:57,NaN,0
99996,77523,65,3866,866,469,2017-11-09 10:26:27,NaN,0
99997,202344,65,3866,866,469,2017-11-09 13:08:40,NaN,0
99998,98534,65,3866,866,469,2017-11-09 11:47:48,NaN,0
99999,35643,66,3866,866,474,2017-11-09 12:40:59,NaN,0

In [ ]:
#연습문제

data = {
    "Animal" : ["Dog", "Cat", "Pig", "Panda"],
    "Name" :["Kong", "Marry", "Sam", "PP"]
}


ani_df = pd.DataFrame(data)

In [ ]:
ani_df

  Animal   Name
0    Dog   Kong
1    Cat  Marry
2    Pig    Sam
3  Panda     PP

In [ ]:
#문자열에 조건 만들기

#데이터프레임[조건].문자열로 바꾸고'.(조건)을 포함하는.
#contains 검색은 대소문자 가림
#ani_df['Name'].str.contains('m') 이 결과는 t/f만 나옴. 조건임!

#ani_df[ani_df['Name'].str.contains('m')]

#	Animal	Name
#2	Pig	Sam

ani_df[ani_df['Name'].str.contains('M')]

# Animal	Name
# 1	Cat	Marry

  Animal   Name
1    Cat  Marry

복습
일반정보별 명령어
    info()
기술정보
    mean, min, max, 1q,2q,3q
    loc iloc
    df[]

조건 관련 연산자
숫자: 사칙연산, !=, ==
문자: contains (''), in/ not in, lower&upper

###apply 활용하여 각 행에 함수 적용하기  #전처리

In [ ]:
#적용할 함수 만듥기

def change_letter(word):
    #x=에 word.upper() 넣고 return에 x 넣어도 좋음
    return word.upper()

In [ ]:
#함수 성능쳌
x = change_letter('I have A cup. happy')
print(x)

I HAVE A CUP. HAPPY

In [ ]:
#데이터 프레임[열이름]: 해당 열 불러오기
#.apply(함수)

#'result'라는 새로운 열로 = 이러한 함수를 적용한 열을 추가해주세요
ani_df['result'] = ani_df['Name'].apply(change_letter)

#결과
ani_df

  Animal   Name result
0    Dog   Kong   KONG
1    Cat  Marry  MARRY
2    Pig    Sam    SAM
3  Panda     PP     PP

In [ ]:
## replace: 특정 데이터를 다른 값으로 대체함

data = {"Peter" : "Man",
        "Sally" : "Woman",
        "Chris" : "Woman",
        "Jack" : "Man"  }

human = pd.DataFrame(data, index =[0])      #index =[0]: 인덱스를 0번으로 넣은 것 이름을 보존하려 더미 데이터 삽입. 결과 보면 알거임.

In [ ]:
human = human.T

In [ ]:
human.columns=['Gender']

In [ ]:
human

      Gender
Peter    Man
Sally  Woman
Chris  Woman
Jack     Man

In [ ]:
#M,W로 바꾸기
#human['Gender'].replace() : 원래하던 방식.
#'Man' -> 'M'
#'Woman' -> 'W'
# 바꿀 내용이 많으면 딕셔너리 활용
human.Gender.replace({"Man" : "M", "Woman" : "W"}, inplace = True)

#inplace를 써야 human 불러야함
human

/tmp/ipykernel_4867/4092252745.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  human.Gender.replace({"Man" : "M", "Woman" : "W"}, inplace = True)

      Gender
Peter      M
Sally      W
Chris      W
Jack       M

## 중요! 집계함수

In [ ]:
#데이터프레임[새 열 이름] = [길이에 맞는 데이터 값. 갯수 맞추기]
human['score'] = [10, 20, 10, 15]

#groupby: 열 기준으로 작용

#['스코어']의 평균()을 구하시오
#단순 통계
human['score'].mean()


#기준을 단순 통계를 주면 안됨. 오류
#'gender' 기준으로 'score' 평균을 내라
#즉, A별 B를 구할 때 유용한 형태
human.groupby('Gender').mean()
#해당 예제 데이터에는 열이 2개 뿐, 열이 2개 이상이면
#human.groupby('city')['score'].sum(): (도시별) [점수] 합을 구해주시오


#다른 통계 함수들
# sum(), mean(),max(), min(), median(), quantile(퍼센트), std (표준편차)

        score
Gender
M        12.5
W        15.0