In [2]:
# #ADsP

# 1. 결측치
#     - 없는 값. null
# 2. 이상치
#     - outlier. 왜곡 가능성
#     - 이상치 찾는 방법:
#         1)ESD 방식: 평균 +- 3표준편차
#         2)IQR 방식: 사분위수 사용. Q3 - 1.5IQR.(낮은 기준) Q3 + Q1.5 IQR(높은 기준) boxplot 형태

In [3]:
import pandas as pd          #행열
import numpy as np          #가상 데이터 및 결측치는 일반적으로 np 자료형으로 표현됨

In [4]:
#np.nan == 결측치 표현하는 자료

data = pd.DataFrame([[1, 2, 3],
                     [2.3, np.nan, 4],
                     [np.nan, np.nan, np.nan],
                     [np.nan, 44, np.nan]])


print(data)

     0     1    2
0  1.0   2.0  3.0
1  2.3   NaN  4.0
2  NaN   NaN  NaN
3  NaN  44.0  NaN

# 결측치 확인 함수:
 -  isnull: 비었느냐. t/f
 - notnull:안 비었느냐. t/f
 - fillna: 누락 데이터를 채워줌
 - dropna: 누락된 데이터가 있는 '축'을 제외
    - 옵션: 1. 어느 방향을 제할 것인가?? axis = o 행 방향으로, =1 열 방향으로

In [5]:
data

     0     1    2
0  1.0   2.0  3.0
1  2.3   NaN  4.0
2  NaN   NaN  NaN
3  NaN  44.0  NaN

In [6]:
#dropna옵션
#axis: 축. 행=0,열=1
#how: any, all
#thresh: 값 기준 설정해 기준을 넘으면 삭제
#subset: 특정 위치 적용

In [7]:
#axis 옵션으로 행 방향으로 데이터 삭제
print(data.dropna(axis=0))

#열 방향으로 데이터 삭제
print(data.dropna(axis=1))

     0    1    2
0  1.0  2.0  3.0
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [8]:
#How: 결측치 모두 삭제하지 않고, 기준을 설정.
    # 일부 nan 삭제(any)

    # 모두 nan 삭제(all)
print(data.dropna(how='all'))               #디폴트는 axis=0 이라 설정하지 않아도 적용이 됨
    #결과
# 0     1    2
# 0  1.0   2.0  3.0
# 1  2.3   NaN  4.0
# 3  NaN  44.0  NaN

     0     1    2
0  1.0   2.0  3.0
1  2.3   NaN  4.0
3  NaN  44.0  NaN

In [9]:
#thresh(임계값) -> 결측치가 몇 개인지 기준을 주고, 이를 넘으면 제거하겠다

data.dropna(thresh=2)

     0    1    2
0  1.0  2.0  3.0
1  2.3  NaN  4.0

In [10]:
#subset: 선 조치 필요(더미 데이터의 컬럼명이 없었기 때문). '부분집합'. 특정 열(행) 기준으로 결측치에 대해 조치하고 싶을 때 사용.
data.columns = ['a', 'b', 'c']
data.dropna(subset=['a'],inplace = True)


#dropna와 같이 옵션들은 꼭 inplace = true 옵션을 넣어줘야 전처리 처리가 원본에 저장이 된답니당

In [11]:
data

     a    b    c
0  1.0  2.0  3.0
1  2.3  NaN  4.0

In [12]:
#채우기 옵션 fillna

#value = 어떤 값으로 채울 것인가? 빈 값을 '어떻게'
#axis = 행 기준, 열 기준 결측값 대체
#inplace: 대체 내용을 원본 데프에 적용?
#limit: 결측값을 몇 개까지 채울 것인가?

기술 통계
-
추론 통계
- 일부 데이터로 전체 예측 (표본 -> 모수)
- 모수적 방법: 숫자로 증명할 수 있음 (평균값으로 대체) mean()
- 비모수적 방법: 숫자로 증명할 수 없는 경우 (중앙값으로 대체) median()
    1. 표본이 너무 작은 경우 (표본이 10 이하)
    2. 이상치가 많은 경우

In [26]:
data = pd.DataFrame([[1, 2, 3],
                     [2.3, np.nan, 4],
                     [np.nan, np.nan, np.nan],
                     [np.nan, 44, np.nan]])


print(data)

     0     1    2
0  1.0   2.0  3.0
1  2.3   NaN  4.0
2  NaN   NaN  NaN
3  NaN  44.0  NaN

In [33]:
# 모수적 방법

#1. 평균값 대체

x = data[0].mean()
data.fillna(value=x)     #특정 열의 빈 곳을 '평균'으로 대체

#2. 중앙값 대체

      0      1     2
0  1.00   2.00  3.00
1  2.30   1.65  4.00
2  1.65   1.65  1.65
3  1.65  44.00  1.65

In [36]:
#fillna 는 들어갈 값이 필수이기에 value 는 꼭 넣을 것
data.fillna(value = 0,axis=0)

     0     1    2
0  1.0   2.0  3.0
1  2.3   0.0  4.0
2  0.0   0.0  0.0
3  0.0  44.0  0.0

In [38]:
#method 옵션: '어떻게 채울 것인가' 에 대한 것. 즉 value가 없어도 가능.
data.fillna(method='ffill')             #foward fill(선행값으로 채우기), back fill(후행 값으로 채우기)
                                #이건 그럼 axis 적용되나?

/tmp/ipykernel_1006/3126274201.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')             #foward fill(선행값으로 채우기), back fill(후행 값으로 채우기)

     0     1    2
0  1.0   2.0  3.0
1  2.3   2.0  4.0
2  2.3   2.0  4.0
3  2.3  44.0  4.0

In [39]:
data.fillna(method='ffill', axis=1)                     #이 옵션에서 행과 열 방향 설정해도 적용이 되는것이냐

/tmp/ipykernel_1006/1730906680.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', axis=1)

     0     1     2
0  1.0   2.0   3.0
1  2.3   2.3   4.0
2  NaN   NaN   NaN
3  NaN  44.0  44.0

In [41]:
#limit: 결측값 몇 개까지 채울 것인가?
#중요: 아무 옵션을 주지 않으면 '열' 기준으로 작용. (다른 함수와 다른 옵션 작동)

#예시: 10명의 데이터(5개 유, 5개 무) -> 80% 살리기면 3개만 살리고 2개는 버리는 것. 여기서 3개 살릴때 사용하는 게 limit
data.fillna(value=0, limit=1)

     0     1    2
0  1.0   2.0  3.0
1  2.3   0.0  4.0
2  0.0   NaN  0.0
3  NaN  44.0  NaN

In [42]:
data.isnull(): t/f

       0      1      2
0  False  False  False
1  False   True  False
2   True   True   True
3   True  False   True

In [44]:
data.notnull() :t/f

       0      1      2
0   True   True   True
1   True  False   True
2  False  False  False
3  False   True  False

In [46]:
# data.info() 하면 한 눈에~

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2 non-null      float64
 1   1       2 non-null      float64
 2   2       2 non-null      float64
dtypes: float64(3)
memory usage: 228.0 bytes

In [47]:
data = {
    'A': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'B': [15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
}
df = pd.DataFrame(data)

In [49]:
df

    A   B
0   1  15
1   2  16
2   3  17
3   4  18
4   5  19
5   6  20
6   7  21
7   8  22
8   9  23
9  10  24

In [52]:
for i in df['A']:
    print(i)

1
2
3
4
5
6
7
8
9
10

In [59]:
#IQR 방식 진행

#1. q1~q3 구해야함 (IQR = Q3 - Q1 구하기)
#2. q1 - 1.5IQR 을 낮은 기준으로
#3. Q3 + 1.5IQR 을 높은 기준으로
#4.모든 데이터를 돌며 3보다 작거나 4보다 큰지 알아보기
#5. 5의 조건에 해당하면 이상치(수염범위)

def iqr(col) :             #왜 함수로 만들게요?: 데이터프레임의 특성이라,  열별(e.g. 점수)로 이상치 탐지해야함,
    #1. q1~q3 구하기
    Q1 = col.quantile(0.25)
    Q2 = col.quantile(0.5)          #col.median()
    Q3 = col.quantile(0.75)
    #IQR 구하기
    IQR = Q3 - Q1

    #2, 3
    lower_band = Q1 - 1.5*IQR
    upper_band = Q3 + 1.5*IQR

    outliers = []
    #4.
    for i in col:                   #열 안에 있는 각 행이 i가 됩니다
        if i < lower_band or i > upper_band:
            outliers.append(i)
    return outliers

In [57]:
temp = pd.read_csv('/content/train.csv')
temp

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [64]:
#함수 어케 설정하더라,,


out = iqr(temp['LotArea'])
print(out)

[50271, 19900, 21000, 21453, 19378, 31770, 22950, 25419, 159000, 19296, 39104, 19138, 18386, 215245, 164660, 20431, 18800, 53107, 34650, 22420, 21750, 70761, 53227, 40094, 32668, 21872, 21780, 25095, 46589, 20896, 18450, 21535, 26178, 115149, 21695, 53504, 21384, 28698, 45600, 17920, 25286, 27650, 24090, 25000, 1300, 21286, 1477, 21750, 29959, 18000, 23257, 17755, 35760, 18030, 35133, 32463, 18890, 24682, 23595, 17871, 36500, 63887, 20781, 25339, 57200, 20544, 19690, 21930, 26142]

In [66]:
len(out)

69