#EDA

0. EDA
 - 문제 분석
 - 실험 디자인 데이터 수집
    - EDA (info, describe, 이상치, 결측치)
    - 파라미터 분석
    
    이를 통해 내가 연구하고자 하는 것의 결과(정규분포)와 유사한 형태의 비교 데이터를 구할 수 있음.


 - 데이터 이용 모델 학습: 머신러닝 분야
 - 모델 성능 검증
    - 성능 개선
 - 결과해석

##머신러닝
1. 지도학습
    - 분류
    - 회귀
2. 비지도학습
    - 군집화
    - 차원 축소: 데이터의 차원을 축소, 특징을 축소하는 것 -> 모델화

    차원 축소를 통해 회귀, 분류, 군집화 하는 식임, 주된 목적은 아님.
    진행 경우: 특성이 너무 많은 경우. (고려되야 할 변수가 너무 많아 정확성이 떨어질 것이 우려됨)
    수많은 독립변수 중 가장 큰 영향을 미치는 것만 남기고 나머지를 없애는 것임.
3. 강화학습
    - 보상 활용
    - 사실 여기는 게임 엔진에 이론까지 얹어야함

# 1. 데이터 분석을 위한 EDA 복습

- 판다스 복습


- 1. 데이터 정보 확인
- 2. 이상치 확인
- 3. 결측치 확인
- 4. 이상치 제거
- 5. 결측치 제거
- 6. 1~5과정에서 시각화 동반.

In [3]:
#판다스 복습
from google.colab import drive
drive.mount('/content/drive', force_remount = True)          #force~: 새로 업데이트된 파일도 감지하는 옵션.런타임 유지하며 새로고침

Mounted at /content/drive

In [4]:
import pandas as pd
import numpy as np
file_path = '/content/drive/MyDrive/새싹과정/my/2주차/gapminder.tsv'

#tsv: tap seperated value. sep = '\t'옵션으로 분리해주기
df = pd.read_csv(file_path, sep ='\t')

df.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [ ]:
#1. 데이터 정보 확인

#일반정보
print(df.info(),'\n')

#통계정보
print(df.describe(),'\n')

#결측치(null,nan,Nan)
print(df.isnull().sum())            #isnull의 합을 구하시오

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB
None

             year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

country      0
continent    0
year         0
lifeExp      0
pop          0
gdpPercap    0
dtype: int64

In [ ]:
#데이터 열 이름

print(df.columns, '\n')
#데이터 행 이름
print(df.index, '\n')

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

RangeIndex(start=0, stop=1704, step=1)

In [ ]:
#특정 열 추출

print(df['continent'],'\n')

#2개 열 이상 (2조건 이상)추출
#내가 했던 게 안되는 이유: 같은 열 조건이니 한 리스트로 묶어야 함. [],[] 형태로는 행, 열로 인식해버림
print(df[ ['continent', 'lifeExp'] ])

expectation = df[ ['continent', 'lifeExp'] ]        #원본 데이터 훼손 예방

0         Asia
1         Asia
2         Asia
3         Asia
4         Asia
         ...
1699    Africa
1700    Africa
1701    Africa
1702    Africa
1703    Africa
Name: continent, Length: 1704, dtype: object

     continent  lifeExp
0         Asia   28.801
1         Asia   30.332
2         Asia   31.997
3         Asia   34.020
4         Asia   36.088
...        ...      ...
1699    Africa   62.351
1700    Africa   60.377
1701    Africa   46.809
1702    Africa   39.989
1703    Africa   43.487

[1704 rows x 2 columns]

In [ ]:
#groupby(A별)[B].통계함수():A별 B.통계함수()값을 구해주세요

expectation.groupby('continent')['lifeExp'].mean()

continent
Africa      48.865330
Americas    64.658737
Asia        60.064903
Europe      71.903686
Oceania     74.326208
Name: lifeExp, dtype: float64

In [ ]:
#1. 새로 데이터 추출
#나라, 인구, gdp 열을 추출하여 result 변수에 정의.

result = df[['country', 'pop', 'gdpPercap']]

#2. 나라별 인구 평균, 나라별 gdp 평균

print(result.groupby('country')['pop'].mean(),'\n')

print(result.groupby('country')['gdpPercap'].mean())

country
Afghanistan           1.582372e+07
Albania               2.580249e+06
Algeria               1.987541e+07
Angola                7.309390e+06
Argentina             2.860224e+07
                          ...
Vietnam               5.456857e+07
West Bank and Gaza    1.848606e+06
Yemen, Rep.           1.084319e+07
Zambia                6.353805e+06
Zimbabwe              7.641966e+06
Name: pop, Length: 142, dtype: float64

country
Afghanistan            802.674598
Albania               3255.366633
Algeria               4426.025973
Angola                3607.100529
Argentina             8955.553783
                         ...
Vietnam               1017.712615
West Bank and Gaza    3759.996781
Yemen, Rep.           1569.274672
Zambia                1358.199409
Zimbabwe               635.858042
Name: gdpPercap, Length: 142, dtype: float64

In [ ]:
# 중복 없는 값 구하기: 특정한 열의 unique

print(df['continent'].unique(),'\n')

#중복 없는 값 개수 구하기
print(df['continent'].nunique(),'\n')

#개수 카운트: value_counts
print(df['continent'].value_counts())

['Asia' 'Europe' 'Africa' 'Americas' 'Oceania']

5

continent
Africa      624
Asia        396
Europe      360
Americas    300
Oceania      24
Name: count, dtype: int64

In [ ]:
df

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [ ]:
#1. 새로운 열을 만들기: 예시= Asia_Afghanistan -> 열이름은 'Source'

#for 문 사용
source = []


for i in range(len(df)):
    #loc[행, 열]: 행이 rangeindex인 경우 '숫자'를 넣어 사용 가능(이름 자체가 숫자라)
    #문자열로 묶었기에 둘 다 더할 수 있음
    temp = str(df.loc[i,'continent'])+ '_' + str(df.loc[i,'country'])      #i번만큼 country값을 추출
    #df.iloc[i,0]과 동일
                                                        #여기까지는 나라+대륙, 문자열 내용이 나옴

    print(temp)
#그러면,, 여기 이후로는
#for문의 결과를 새로운 리스트에 넣고,
#데이터 프레임 형식으로 만들고
#source라는 새로운 열 이름으로 만들기

source.append(temp)          #for문 결과 새로운 리스트에 넣음.

#추가 -
len(source) == len (df)

#최종적 열 생성
#df['source'] = source

df
#얘는 뭐지 얘로 써도 되는거 아닌가? 근데 왜 안돼
#source = pd.DataFrame(temp)     #데이터 프레임화,,,

Asia_Afghanistan
Asia_Afghanistan
Asia_Afghanistan
Asia_Afghanistan
Asia_Afghanistan
Asia_Afghanistan
Asia_Afghanistan
Asia_Afghanistan
Asia_Afghanistan
Asia_Afghanistan
Asia_Afghanistan
Asia_Afghanistan
Europe_Albania
Europe_Albania
Europe_Albania
Europe_Albania
Europe_Albania
Europe_Albania
Europe_Albania
Europe_Albania
Europe_Albania
Europe_Albania
Europe_Albania
Europe_Albania
Africa_Algeria
Africa_Algeria
Africa_Algeria
Africa_Algeria
Africa_Algeria
Africa_Algeria
Africa_Algeria
Africa_Algeria
Africa_Algeria
Africa_Algeria
Africa_Algeria
Africa_Algeria
Africa_Angola
Africa_Angola
Africa_Angola
Africa_Angola
Africa_Angola
Africa_Angola
Africa_Angola
Africa_Angola
Africa_Angola
Africa_Angola
Africa_Angola
Africa_Angola
Americas_Argentina
Americas_Argentina
Americas_Argentina
Americas_Argentina
Americas_Argentina
Americas_Argentina
Americas_Argentina
Americas_Argentina
Americas_Argentina
Americas_Argentina
Americas_Argentina
Americas_Argentina
Oceania_Australia
Oceania_Australia
Oceania_Australia
Oceania_Australia
Oceania_Australia
Oceania_Australia
Oceania_Australia
Oceania_Australia
Oceania_Australia
Oceania_Australia
Oceania_Australia
Oceania_Australia
Europe_Austria
Europe_Austria
Europe_Austria
Europe_Austria
Europe_Austria
Europe_Austria
Europe_Austria
Europe_Austria
Europe_Austria
Europe_Austria
Europe_Austria
Europe_Austria
Asia_Bahrain
Asia_Bahrain
Asia_Bahrain
Asia_Bahrain
Asia_Bahrain
Asia_Bahrain
Asia_Bahrain
Asia_Bahrain
Asia_Bahrain
Asia_Bahrain
Asia_Bahrain
Asia_Bahrain
Asia_Bangladesh
Asia_Bangladesh
Asia_Bangladesh
Asia_Bangladesh
Asia_Bangladesh
Asia_Bangladesh
Asia_Bangladesh
Asia_Bangladesh
Asia_Bangladesh
Asia_Bangladesh
Asia_Bangladesh
Asia_Bangladesh
Europe_Belgium
Europe_Belgium
Europe_Belgium
Europe_Belgium
Europe_Belgium
Europe_Belgium
Europe_Belgium
Europe_Belgium
Europe_Belgium
Europe_Belgium
Europe_Belgium
Europe_Belgium
Africa_Benin
Africa_Benin
Africa_Benin
Africa_Benin
Africa_Benin
Africa_Benin
Africa_Benin
Africa_Benin
Africa_Benin
Africa_Benin
Africa_Benin
Africa_Benin
Americas_Bolivia
Americas_Bolivia
Americas_Bolivia
Americas_Bolivia
Americas_Bolivia
Americas_Bolivia
Americas_Bolivia
Americas_Bolivia
Americas_Bolivia
Americas_Bolivia
Americas_Bolivia
Americas_Bolivia
Europe_Bosnia and Herzegovina
Europe_Bosnia and Herzegovina
Europe_Bosnia and Herzegovina
Europe_Bosnia and Herzegovina
Europe_Bosnia and Herzegovina
Europe_Bosnia and Herzegovina
Europe_Bosnia and Herzegovina
Europe_Bosnia and Herzegovina
Europe_Bosnia and Herzegovina
Europe_Bosnia and Herzegovina
Europe_Bosnia and Herzegovina
Europe_Bosnia and Herzegovina
Africa_Botswana
Africa_Botswana
Africa_Botswana
Africa_Botswana
Africa_Botswana
Africa_Botswana
Africa_Botswana
Africa_Botswana
Africa_Botswana
Africa_Botswana
Africa_Botswana
Africa_Botswana
Americas_Brazil
Americas_Brazil
Americas_Brazil
Americas_Brazil
Americas_Brazil
Americas_Brazil
Americas_Brazil
Americas_Brazil
Americas_Brazil
Americas_Brazil
Americas_Brazil
Americas_Brazil
Europe_Bulgaria
Europe_Bulgaria
Europe_Bulgaria
Europe_Bulgaria
Europe_Bulgaria
Europe_Bulgaria
Europe_Bulgaria
Europe_Bulgaria
Europe_Bulgaria
Europe_Bulgaria
Europe_Bulgaria
Europe_Bulgaria
Africa_Burkina Faso
Africa_Burkina Faso
Africa_Burkina Faso
Africa_Burkina Faso
Africa_Burkina Faso
Africa_Burkina Faso
Africa_Burkina Faso
Africa_Burkina Faso
Africa_Burkina Faso
Africa_Burkina Faso
Africa_Burkina Faso
Africa_Burkina Faso
Africa_Burundi
Africa_Burundi
Africa_Burundi
Africa_Burundi
Africa_Burundi
Africa_Burundi
Africa_Burundi
Africa_Burundi
Africa_Burundi
Africa_Burundi
Africa_Burundi
Africa_Burundi
Asia_Cambodia
Asia_Cambodia
Asia_Cambodia
Asia_Cambodia
Asia_Cambodia
Asia_Cambodia
Asia_Cambodia
Asia_Cambodia
Asia_Cambodia
Asia_Cambodia
Asia_Cambodia
Asia_Cambodia
Africa_Cameroon
Africa_Cameroon
Africa_Cameroon
Africa_Cameroon
Africa_Cameroon
Africa_Cameroon
Africa_Cameroon
Africa_Cameroon
Africa_Cameroon
Africa_Cameroon
Africa_Cameroon
Africa_Cameroon
Americas_Canada
Americas_Canada
Americas_Canada
Americas_Canada
Americas_Canada
Americas_Canada
Americas_Canada
Americas_Canada
Americas_Canada
Americas_Canada
Americas_Canada
Americas_Canada
Africa_Central African Republic
Africa_Central African Republic
Africa_Central African Republic
Africa_Central African Republic
Africa_Central African Republic
Africa_Central African Republic
Africa_Central African Republic
Africa_Central African Republic
Africa_Central African Republic
Africa_Central African Republic
Africa_Central African Republic
Africa_Central African Republic
Africa_Chad
Africa_Chad
Africa_Chad
Africa_Chad
Africa_Chad
Africa_Chad
Africa_Chad
Africa_Chad
Africa_Chad
Africa_Chad
Africa_Chad
Africa_Chad
Americas_Chile
Americas_Chile
Americas_Chile
Americas_Chile
Americas_Chile
Americas_Chile
Americas_Chile
Americas_Chile
Americas_Chile
Americas_Chile
Americas_Chile
Americas_Chile
Asia_China
Asia_China
Asia_China
Asia_China
Asia_China
Asia_China
Asia_China
Asia_China
Asia_China
Asia_China
Asia_China
Asia_China
Americas_Colombia
Americas_Colombia
Americas_Colombia
Americas_Colombia
Americas_Colombia
Americas_Colombia
Americas_Colombia
Americas_Colombia
Americas_Colombia
Americas_Colombia
Americas_Colombia
Americas_Colombia
Africa_Comoros
Africa_Comoros
Africa_Comoros
Africa_Comoros
Africa_Comoros
Africa_Comoros
Africa_Comoros
Africa_Comoros
Africa_Comoros
Africa_Comoros
Africa_Comoros
Africa_Comoros
Africa_Congo, Dem. Rep.
Africa_Congo, Dem. Rep.
Africa_Congo, Dem. Rep.
Africa_Congo, Dem. Rep.
Africa_Congo, Dem. Rep.
Africa_Congo, Dem. Rep.
Africa_Congo, Dem. Rep.
Africa_Congo, Dem. Rep.
Africa_Congo, Dem. Rep.
Africa_Congo, Dem. Rep.
Africa_Congo, Dem. Rep.
Africa_Congo, Dem. Rep.
Africa_Congo, Rep.
Africa_Congo, Rep.
Africa_Congo, Rep.
Africa_Congo, Rep.
Africa_Congo, Rep.
Africa_Congo, Rep.
Africa_Congo, Rep.
Africa_Congo, Rep.
Africa_Congo, Rep.
Africa_Congo, Rep.
Africa_Congo, Rep.
Africa_Congo, Rep.
Americas_Costa Rica
Americas_Costa Rica
Americas_Costa Rica
Americas_Costa Rica
Americas_Costa Rica
Americas_Costa Rica
Americas_Costa Rica
Americas_Costa Rica
Americas_Costa Rica
Americas_Costa Rica
Americas_Costa Rica
Americas_Costa Rica
Africa_Cote d'Ivoire
Africa_Cote d'Ivoire
Africa_Cote d'Ivoire
Africa_Cote d'Ivoire
Africa_Cote d'Ivoire
Africa_Cote d'Ivoire
Africa_Cote d'Ivoire
Africa_Cote d'Ivoire
Africa_Cote d'Ivoire
Africa_Cote d'Ivoire
Africa_Cote d'Ivoire
Africa_Cote d'Ivoire
Europe_Croatia
Europe_Croatia
Europe_Croatia
Europe_Croatia
Europe_Croatia
Europe_Croatia
Europe_Croatia
Europe_Croatia
Europe_Croatia
Europe_Croatia
Europe_Croatia
Europe_Croatia
Americas_Cuba
Americas_Cuba
Americas_Cuba
Americas_Cuba
Americas_Cuba
Americas_Cuba
Americas_Cuba
Americas_Cuba
Americas_Cuba
Americas_Cuba
Americas_Cuba
Americas_Cuba
Europe_Czech Republic
Europe_Czech Republic
Europe_Czech Republic
Europe_Czech Republic
Europe_Czech Republic
Europe_Czech Republic
Europe_Czech Republic
Europe_Czech Republic
Europe_Czech Republic
Europe_Czech Republic
Europe_Czech Republic
Europe_Czech Republic
Europe_Denmark
Europe_Denmark
Europe_Denmark
Europe_Denmark
Europe_Denmark
Europe_Denmark
Europe_Denmark
Europe_Denmark
Europe_Denmark
Europe_Denmark
Europe_Denmark
Europe_Denmark
Africa_Djibouti
Africa_Djibouti
Africa_Djibouti
Africa_Djibouti
Africa_Djibouti
Africa_Djibouti
Africa_Djibouti
Africa_Djibouti
Africa_Djibouti
Africa_Djibouti
Africa_Djibouti
Africa_Djibouti
Americas_Dominican Republic
Americas_Dominican Republic
Americas_Dominican Republic
Americas_Dominican Republic
Americas_Dominican Republic
Americas_Dominican Republic
Americas_Dominican Republic
Americas_Dominican Republic
Americas_Dominican Republic
Americas_Dominican Republic
Americas_Dominican Republic
Americas_Dominican Republic
Americas_Ecuador
Americas_Ecuador
Americas_Ecuador
Americas_Ecuador
Americas_Ecuador
Americas_Ecuador
Americas_Ecuador
Americas_Ecuador
Americas_Ecuador
Americas_Ecuador
Americas_Ecuador
Americas_Ecuador
Africa_Egypt
Africa_Egypt
Africa_Egypt
Africa_Egypt
Africa_Egypt
Africa_Egypt
Africa_Egypt
Africa_Egypt
Africa_Egypt
Africa_Egypt
Africa_Egypt
Africa_Egypt
Americas_El Salvador
Americas_El Salvador
Americas_El Salvador
Americas_El Salvador
Americas_El Salvador
Americas_El Salvador
Americas_El Salvador
Americas_El Salvador
Americas_El Salvador
Americas_El Salvador
Americas_El Salvador
Americas_El Salvador
Africa_Equatorial Guinea
Africa_Equatorial Guinea
Africa_Equatorial Guinea
Africa_Equatorial Guinea
Africa_Equatorial Guinea
Africa_Equatorial Guinea
Africa_Equatorial Guinea
Africa_Equatorial Guinea
Africa_Equatorial Guinea
Africa_Equatorial Guinea
Africa_Equatorial Guinea
Africa_Equatorial Guinea
Africa_Eritrea
Africa_Eritrea
Africa_Eritrea
Africa_Eritrea
Africa_Eritrea
Africa_Eritrea
Africa_Eritrea
Africa_Eritrea
Africa_Eritrea
Africa_Eritrea
Africa_Eritrea
Africa_Eritrea
Africa_Ethiopia
Africa_Ethiopia
Africa_Ethiopia
Africa_Ethiopia
Africa_Ethiopia
Africa_Ethiopia
Africa_Ethiopia
Africa_Ethiopia
Africa_Ethiopia
Africa_Ethiopia
Africa_Ethiopia
Africa_Ethiopia
Europe_Finland
Europe_Finland
Europe_Finland
Europe_Finland
Europe_Finland
Europe_Finland
Europe_Finland
Europe_Finland
Europe_Finland
Europe_Finland
Europe_Finland
Europe_Finland
Europe_France
Europe_France
Europe_France
Europe_France
Europe_France
Europe_France
Europe_France
Europe_France
Europe_France
Europe_France
Europe_France
Europe_France
Africa_Gabon
Africa_Gabon
Africa_Gabon
Africa_Gabon
Africa_Gabon
Africa_Gabon
Africa_Gabon
Africa_Gabon
Africa_Gabon
Africa_Gabon
Africa_Gabon
Africa_Gabon
Africa_Gambia
Africa_Gambia
Africa_Gambia
Africa_Gambia
Africa_Gambia
Africa_Gambia
Africa_Gambia
Africa_Gambia
Africa_Gambia
Africa_Gambia
Africa_Gambia
Africa_Gambia
Europe_Germany
Europe_Germany
Europe_Germany
Europe_Germany
Europe_Germany
Europe_Germany
Europe_Germany
Europe_Germany
Europe_Germany
Europe_Germany
Europe_Germany
Europe_Germany
Africa_Ghana
Africa_Ghana
Africa_Ghana
Africa_Ghana
Africa_Ghana
Africa_Ghana
Africa_Ghana
Africa_Ghana
Africa_Ghana
Africa_Ghana
Africa_Ghana
Africa_Ghana
Europe_Greece
Europe_Greece
Europe_Greece
Europe_Greece
Europe_Greece
Europe_Greece
Europe_Greece
Europe_Greece
Europe_Greece
Europe_Greece
Europe_Greece
Europe_Greece
Americas_Guatemala
Americas_Guatemala
Americas_Guatemala
Americas_Guatemala
Americas_Guatemala
Americas_Guatemala
Americas_Guatemala
Americas_Guatemala
Americas_Guatemala
Americas_Guatemala
Americas_Guatemala
Americas_Guatemala
Africa_Guinea
Africa_Guinea
Africa_Guinea
Africa_Guinea
Africa_Guinea
Africa_Guinea
Africa_Guinea
Africa_Guinea
Africa_Guinea
Africa_Guinea
Africa_Guinea
Africa_Guinea
Africa_Guinea-Bissau
Africa_Guinea-Bissau
Africa_Guinea-Bissau
Africa_Guinea-Bissau
Africa_Guinea-Bissau
Africa_Guinea-Bissau
Africa_Guinea-Bissau
Africa_Guinea-Bissau
Africa_Guinea-Bissau
Africa_Guinea-Bissau
Africa_Guinea-Bissau
Africa_Guinea-Bissau
Americas_Haiti
Americas_Haiti
Americas_Haiti
Americas_Haiti
Americas_Haiti
Americas_Haiti
Americas_Haiti
Americas_Haiti
Americas_Haiti
Americas_Haiti
Americas_Haiti
Americas_Haiti
Americas_Honduras
Americas_Honduras
Americas_Honduras
Americas_Honduras
Americas_Honduras
Americas_Honduras
Americas_Honduras
Americas_Honduras
Americas_Honduras
Americas_Honduras
Americas_Honduras
Americas_Honduras
Asia_Hong Kong, China
Asia_Hong Kong, China
Asia_Hong Kong, China
Asia_Hong Kong, China
Asia_Hong Kong, China
Asia_Hong Kong, China
Asia_Hong Kong, China
Asia_Hong Kong, China
Asia_Hong Kong, China
Asia_Hong Kong, China
Asia_Hong Kong, China
Asia_Hong Kong, China
Europe_Hungary
Europe_Hungary
Europe_Hungary
Europe_Hungary
Europe_Hungary
Europe_Hungary
Europe_Hungary
Europe_Hungary
Europe_Hungary
Europe_Hungary
Europe_Hungary
Europe_Hungary
Europe_Iceland
Europe_Iceland
Europe_Iceland
Europe_Iceland
Europe_Iceland
Europe_Iceland
Europe_Iceland
Europe_Iceland
Europe_Iceland
Europe_Iceland
Europe_Iceland
Europe_Iceland
Asia_India
Asia_India
Asia_India
Asia_India
Asia_India
Asia_India
Asia_India
Asia_India
Asia_India
Asia_India
Asia_India
Asia_India
Asia_Indonesia
Asia_Indonesia
Asia_Indonesia
Asia_Indonesia
Asia_Indonesia
Asia_Indonesia
Asia_Indonesia
Asia_Indonesia
Asia_Indonesia
Asia_Indonesia
Asia_Indonesia
Asia_Indonesia
Asia_Iran
Asia_Iran
Asia_Iran
Asia_Iran
Asia_Iran
Asia_Iran
Asia_Iran
Asia_Iran
Asia_Iran
Asia_Iran
Asia_Iran
Asia_Iran
Asia_Iraq
Asia_Iraq
Asia_Iraq
Asia_Iraq
Asia_Iraq
Asia_Iraq
Asia_Iraq
Asia_Iraq
Asia_Iraq
Asia_Iraq
Asia_Iraq
Asia_Iraq
Europe_Ireland
Europe_Ireland
Europe_Ireland
Europe_Ireland
Europe_Ireland
Europe_Ireland
Europe_Ireland
Europe_Ireland
Europe_Ireland
Europe_Ireland
Europe_Ireland
Europe_Ireland
Asia_Israel
Asia_Israel
Asia_Israel
Asia_Israel
Asia_Israel
Asia_Israel
Asia_Israel
Asia_Israel
Asia_Israel
Asia_Israel
Asia_Israel
Asia_Israel
Europe_Italy
Europe_Italy
Europe_Italy
Europe_Italy
Europe_Italy
Europe_Italy
Europe_Italy
Europe_Italy
Europe_Italy
Europe_Italy
Europe_Italy
Europe_Italy
Americas_Jamaica
Americas_Jamaica
Americas_Jamaica
Americas_Jamaica
Americas_Jamaica
Americas_Jamaica
Americas_Jamaica
Americas_Jamaica
Americas_Jamaica
Americas_Jamaica
Americas_Jamaica
Americas_Jamaica
Asia_Japan
Asia_Japan
Asia_Japan
Asia_Japan
Asia_Japan
Asia_Japan
Asia_Japan
Asia_Japan
Asia_Japan
Asia_Japan
Asia_Japan
Asia_Japan
Asia_Jordan
Asia_Jordan
Asia_Jordan
Asia_Jordan
Asia_Jordan
Asia_Jordan
Asia_Jordan
Asia_Jordan
Asia_Jordan
Asia_Jordan
Asia_Jordan
Asia_Jordan
Africa_Kenya
Africa_Kenya
Africa_Kenya
Africa_Kenya
Africa_Kenya
Africa_Kenya
Africa_Kenya
Africa_Kenya
Africa_Kenya
Africa_Kenya
Africa_Kenya
Africa_Kenya
Asia_Korea, Dem. Rep.
Asia_Korea, Dem. Rep.
Asia_Korea, Dem. Rep.
Asia_Korea, Dem. Rep.
Asia_Korea, Dem. Rep.
Asia_Korea, Dem. Rep.
Asia_Korea, Dem. Rep.
Asia_Korea, Dem. Rep.
Asia_Korea, Dem. Rep.
Asia_Korea, Dem. Rep.
Asia_Korea, Dem. Rep.
Asia_Korea, Dem. Rep.
Asia_Korea, Rep.
Asia_Korea, Rep.
Asia_Korea, Rep.
Asia_Korea, Rep.
Asia_Korea, Rep.
Asia_Korea, Rep.
Asia_Korea, Rep.
Asia_Korea, Rep.
Asia_Korea, Rep.
Asia_Korea, Rep.
Asia_Korea, Rep.
Asia_Korea, Rep.
Asia_Kuwait
Asia_Kuwait
Asia_Kuwait
Asia_Kuwait
Asia_Kuwait
Asia_Kuwait
Asia_Kuwait
Asia_Kuwait
Asia_Kuwait
Asia_Kuwait
Asia_Kuwait
Asia_Kuwait
Asia_Lebanon
Asia_Lebanon
Asia_Lebanon
Asia_Lebanon
Asia_Lebanon
Asia_Lebanon
Asia_Lebanon
Asia_Lebanon
Asia_Lebanon
Asia_Lebanon
Asia_Lebanon
Asia_Lebanon
Africa_Lesotho
Africa_Lesotho
Africa_Lesotho
Africa_Lesotho
Africa_Lesotho
Africa_Lesotho
Africa_Lesotho
Africa_Lesotho
Africa_Lesotho
Africa_Lesotho
Africa_Lesotho
Africa_Lesotho
Africa_Liberia
Africa_Liberia
Africa_Liberia
Africa_Liberia
Africa_Liberia
Africa_Liberia
Africa_Liberia
Africa_Liberia
Africa_Liberia
Africa_Liberia
Africa_Liberia
Africa_Liberia
Africa_Libya
Africa_Libya
Africa_Libya
Africa_Libya
Africa_Libya
Africa_Libya
Africa_Libya
Africa_Libya
Africa_Libya
Africa_Libya
Africa_Libya
Africa_Libya
Africa_Madagascar
Africa_Madagascar
Africa_Madagascar
Africa_Madagascar
Africa_Madagascar
Africa_Madagascar
Africa_Madagascar
Africa_Madagascar
Africa_Madagascar
Africa_Madagascar
Africa_Madagascar
Africa_Madagascar
Africa_Malawi
Africa_Malawi
Africa_Malawi
Africa_Malawi
Africa_Malawi
Africa_Malawi
Africa_Malawi
Africa_Malawi
Africa_Malawi
Africa_Malawi
Africa_Malawi
Africa_Malawi
Asia_Malaysia
Asia_Malaysia
Asia_Malaysia
Asia_Malaysia
Asia_Malaysia
Asia_Malaysia
Asia_Malaysia
Asia_Malaysia
Asia_Malaysia
Asia_Malaysia
Asia_Malaysia
Asia_Malaysia
Africa_Mali
Africa_Mali
Africa_Mali
Africa_Mali
Africa_Mali
Africa_Mali
Africa_Mali
Africa_Mali
Africa_Mali
Africa_Mali
Africa_Mali
Africa_Mali
Africa_Mauritania
Africa_Mauritania
Africa_Mauritania
Africa_Mauritania
Africa_Mauritania
Africa_Mauritania
Africa_Mauritania
Africa_Mauritania
Africa_Mauritania
Africa_Mauritania
Africa_Mauritania
Africa_Mauritania
Africa_Mauritius
Africa_Mauritius
Africa_Mauritius
Africa_Mauritius
Africa_Mauritius
Africa_Mauritius
Africa_Mauritius
Africa_Mauritius
Africa_Mauritius
Africa_Mauritius
Africa_Mauritius
Africa_Mauritius
Americas_Mexico
Americas_Mexico
Americas_Mexico
Americas_Mexico
Americas_Mexico
Americas_Mexico
Americas_Mexico
Americas_Mexico
Americas_Mexico
Americas_Mexico
Americas_Mexico
Americas_Mexico
Asia_Mongolia
Asia_Mongolia
Asia_Mongolia
Asia_Mongolia
Asia_Mongolia
Asia_Mongolia
Asia_Mongolia
Asia_Mongolia
Asia_Mongolia
Asia_Mongolia
Asia_Mongolia
Asia_Mongolia
Europe_Montenegro
Europe_Montenegro
Europe_Montenegro
Europe_Montenegro
Europe_Montenegro
Europe_Montenegro
Europe_Montenegro
Europe_Montenegro
Europe_Montenegro
Europe_Montenegro
Europe_Montenegro
Europe_Montenegro
Africa_Morocco
Africa_Morocco
Africa_Morocco
Africa_Morocco
Africa_Morocco
Africa_Morocco
Africa_Morocco
Africa_Morocco
Africa_Morocco
Africa_Morocco
Africa_Morocco
Africa_Morocco
Africa_Mozambique
Africa_Mozambique
Africa_Mozambique
Africa_Mozambique
Africa_Mozambique
Africa_Mozambique
Africa_Mozambique
Africa_Mozambique
Africa_Mozambique
Africa_Mozambique
Africa_Mozambique
Africa_Mozambique
Asia_Myanmar
Asia_Myanmar
Asia_Myanmar
Asia_Myanmar
Asia_Myanmar
Asia_Myanmar
Asia_Myanmar
Asia_Myanmar
Asia_Myanmar
Asia_Myanmar
Asia_Myanmar
Asia_Myanmar
Africa_Namibia
Africa_Namibia
Africa_Namibia
Africa_Namibia
Africa_Namibia
Africa_Namibia
Africa_Namibia
Africa_Namibia
Africa_Namibia
Africa_Namibia
Africa_Namibia
Africa_Namibia
Asia_Nepal
Asia_Nepal
Asia_Nepal
Asia_Nepal
Asia_Nepal
Asia_Nepal
Asia_Nepal
Asia_Nepal
Asia_Nepal
Asia_Nepal
Asia_Nepal
Asia_Nepal
Europe_Netherlands
Europe_Netherlands
Europe_Netherlands
Europe_Netherlands
Europe_Netherlands
Europe_Netherlands
Europe_Netherlands
Europe_Netherlands
Europe_Netherlands
Europe_Netherlands
Europe_Netherlands
Europe_Netherlands
Oceania_New Zealand
Oceania_New Zealand
Oceania_New Zealand
Oceania_New Zealand
Oceania_New Zealand
Oceania_New Zealand
Oceania_New Zealand
Oceania_New Zealand
Oceania_New Zealand
Oceania_New Zealand
Oceania_New Zealand
Oceania_New Zealand
Americas_Nicaragua
Americas_Nicaragua
Americas_Nicaragua
Americas_Nicaragua
Americas_Nicaragua
Americas_Nicaragua
Americas_Nicaragua
Americas_Nicaragua
Americas_Nicaragua
Americas_Nicaragua
Americas_Nicaragua
Americas_Nicaragua
Africa_Niger
Africa_Niger
Africa_Niger
Africa_Niger
Africa_Niger
Africa_Niger
Africa_Niger
Africa_Niger
Africa_Niger
Africa_Niger
Africa_Niger
Africa_Niger
Africa_Nigeria
Africa_Nigeria
Africa_Nigeria
Africa_Nigeria
Africa_Nigeria
Africa_Nigeria
Africa_Nigeria
Africa_Nigeria
Africa_Nigeria
Africa_Nigeria
Africa_Nigeria
Africa_Nigeria
Europe_Norway
Europe_Norway
Europe_Norway
Europe_Norway
Europe_Norway
Europe_Norway
Europe_Norway
Europe_Norway
Europe_Norway
Europe_Norway
Europe_Norway
Europe_Norway
Asia_Oman
Asia_Oman
Asia_Oman
Asia_Oman
Asia_Oman
Asia_Oman
Asia_Oman
Asia_Oman
Asia_Oman
Asia_Oman
Asia_Oman
Asia_Oman
Asia_Pakistan
Asia_Pakistan
Asia_Pakistan
Asia_Pakistan
Asia_Pakistan
Asia_Pakistan
Asia_Pakistan
Asia_Pakistan
Asia_Pakistan
Asia_Pakistan
Asia_Pakistan
Asia_Pakistan
Americas_Panama
Americas_Panama
Americas_Panama
Americas_Panama
Americas_Panama
Americas_Panama
Americas_Panama
Americas_Panama
Americas_Panama
Americas_Panama
Americas_Panama
Americas_Panama
Americas_Paraguay
Americas_Paraguay
Americas_Paraguay
Americas_Paraguay
Americas_Paraguay
Americas_Paraguay
Americas_Paraguay
Americas_Paraguay
Americas_Paraguay
Americas_Paraguay
Americas_Paraguay
Americas_Paraguay
Americas_Peru
Americas_Peru
Americas_Peru
Americas_Peru
Americas_Peru
Americas_Peru
Americas_Peru
Americas_Peru
Americas_Peru
Americas_Peru
Americas_Peru
Americas_Peru
Asia_Philippines
Asia_Philippines
Asia_Philippines
Asia_Philippines
Asia_Philippines
Asia_Philippines
Asia_Philippines
Asia_Philippines
Asia_Philippines
Asia_Philippines
Asia_Philippines
Asia_Philippines
Europe_Poland
Europe_Poland
Europe_Poland
Europe_Poland
Europe_Poland
Europe_Poland
Europe_Poland
Europe_Poland
Europe_Poland
Europe_Poland
Europe_Poland
Europe_Poland
Europe_Portugal
Europe_Portugal
Europe_Portugal
Europe_Portugal
Europe_Portugal
Europe_Portugal
Europe_Portugal
Europe_Portugal
Europe_Portugal
Europe_Portugal
Europe_Portugal
Europe_Portugal

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [ ]:
df['source'] = df['continent']+df['country']
#둘 다 문자열이라 가능함

In [ ]:
#2. lifeExp 열의 모든 데이터를 정수로 변환

#df['lifeExp'] = int(df['lifeExp'])
#astype 활용
df['lifeExp'] = df['lifeExp'].astype(int)

In [ ]:
#함수 활용
def change(data):
    return int(data)

df['lifeExp'] = df['lifeExp'].apply(change)

In [ ]:
df

,country,continent,year,lifeExp,pop,gdpPercap,source
0,Afghanistan,Asia,1952년,28,8425333,779.445314,AsiaAfghanistan
1,Afghanistan,Asia,1957년,30,9240934,820.853030,AsiaAfghanistan
2,Afghanistan,Asia,1962년,31,10267083,853.100710,AsiaAfghanistan
3,Afghanistan,Asia,1967년,34,11537966,836.197138,AsiaAfghanistan
4,Afghanistan,Asia,1972년,36,13079460,739.981106,AsiaAfghanistan
...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987년,62,9216418,706.157306,AfricaZimbabwe
1700,Zimbabwe,Africa,1992년,60,10704340,693.420786,AfricaZimbabwe
1701,Zimbabwe,Africa,1997년,46,11404948,792.449960,AfricaZimbabwe
1702,Zimbabwe,Africa,2002년,39,11926563,672.038623,AfricaZimbabwe
1703,Zimbabwe,Africa,2007년,43,12311143,469.709298,AfricaZimbabwe

In [ ]:
#3. year열의 모든 데이터. 1952 -> 1952년 으로
#데이터프레임.apply(함수이름)
#데이터프레임의 모든 행에 '함수'를 적용하는 것
#data => df이 데이터프레임 '행'

            #(매개변수)
def add_str(data):
    return f'{data}년'

    #apply 역할: 데이터프레임의 각 줄에 함수를 적용시킴
    #이때 함수(매개변수) -> 매개변수는 df의 해당하는 열의 데이터가 넘어감
df['year'] = df ['year'].apply(add_str)

df.head()

,country,continent,year,lifeExp,pop,gdpPercap,source
0,Afghanistan,Asia,1952년,28.801,8425333,779.445314,AsiaAfghanistan
1,Afghanistan,Asia,1957년,30.332,9240934,820.853030,AsiaAfghanistan
2,Afghanistan,Asia,1962년,31.997,10267083,853.100710,AsiaAfghanistan
3,Afghanistan,Asia,1967년,34.020,11537966,836.197138,AsiaAfghanistan
4,Afghanistan,Asia,1972년,36.088,13079460,739.981106,AsiaAfghanistan

In [ ]:
#a*b 함수

def multi(a,b):
    #ab는 받기
    #print(a*b)
    return a*b #return은 받는 변수가 필요함
result = multi(1,4)     #괄호 내 숫자만 바꾸면 되는 편
print(result)

4

In [ ]:
#내가 생각한 답:

#1. 새로운 열을 만들기(in 머신러닝, 파생변수 만들기): 예시= Asia_Afghanistan -> 열이름은 'Source'
#-> 1주차 4차시 4번 파일 참고

#source = 각 열을 추출하고 합치기 continent + country
# df['continet']
# df['country']

#2. lifeExp 열의 모든 데이터를 정수로 변환

# life = []
# life.append(int(df['lifeExp']))

#df.astype('lifeExp')
#print(type(df['lifeExp'])): 시리즈



#3. year열의 모든 데이터. 1952 -> 1952년 으로


#year 추출, 후 '년' 합친 후 변수 정의

years = []

for i in range(len(df)):
    yearn= str(df.loc[i,'year']) + '년'

years.append(yearn)         #여기까지는 years라는 리스트에 yearn이라는 값 넣은 것.
df[years] = years

print(df[years])

    #아 이건 왜 안되냐면 새로운 열을 추가하는 작업이라 그럼!!! 함수를 활용하는 것이 더 적합함


                    #그러면 새로운 변수로 정의를 해서 프린트 해보삼

                    # newy = years
                    # print(newy)

In [5]:
import seaborn as sns

tips = sns.load_dataset('tips')
len(tips)
#tips.head()

244

In [10]:
#파생변수 만들기
# 1. 팁/전체 계산 금액 으로 전체 금액 대비 팁의 비율 계산해 tips['ratio']열 생성

#나: 복잡하게 돌아가는듯 일단 자료를 파악하삼, 문제에서 요구하는 것은 수치/수치라 간단히 작성 가능
tips['ratio'] = tips['tip']/tips['total_bill']
tips.head()

#2. '성별'이 'Male'인 경우, '남, 'Female'인 경우 '여'로 적용.

#replace(조건)-> '열'에 있는 데이터가 '조건'을 만족하도록 대체.
#조건은 딕셔너리 활용: {'Male':'남', 'Female' :'여'}
tips['sex'] = tips['sex'].replace({'Male':'남', 'Female' :'여'})
tips


#3. size가 4 이상인 경우 '단체 손님, 이하인 경우 '-'을 적용해 tips['type']열에 넣어주기

def customer_type(x):
    if x >= 4:
        return '단체손님'
    else:
        return '-'


tips['type'] = tips['size'].apply(customer_type)
tips

     total_bill   tip sex smoker   day    time  size     ratio  type
0         16.99  1.01   여     No   Sun  Dinner     2  0.059447     -
1         10.34  1.66   남     No   Sun  Dinner     3  0.160542     -
2         21.01  3.50   남     No   Sun  Dinner     3  0.166587     -
3         23.68  3.31   남     No   Sun  Dinner     2  0.139780     -
4         24.59  3.61   여     No   Sun  Dinner     4  0.146808  단체손님
..          ...   ...  ..    ...   ...     ...   ...       ...   ...
239       29.03  5.92   남     No   Sat  Dinner     3  0.203927     -
240       27.18  2.00   여    Yes   Sat  Dinner     2  0.073584     -
241       22.67  2.00   남    Yes   Sat  Dinner     2  0.088222     -
242       17.82  1.75   남     No   Sat  Dinner     2  0.098204     -
243       18.78  3.00   여     No  Thur  Dinner     2  0.159744     -

[244 rows x 9 columns]

In [9]:
 tips ['tip'] / tips ['total_bill']

0      0.059447
1      0.160542
2      0.166587
3      0.139780
4      0.146808
         ...
239    0.203927
240    0.073584
241    0.088222
242    0.098204
243    0.159744
Length: 244, dtype: float64

In [11]:
# 1. 팁/전체 계산 금액 으로 전체 금액 대비 팁의 비율 계산해 tips['ratio']열 생성
#함수냐 for 문이냐 고민이 되는구먼.

#문제점: 행/행 결과가 뭉텅이로 리스트에 넣어서 그럼
#해결점: 위치로 잡아서 리스트로 넣어줘야 원하는 결과가 나올것

ratio =[]

for i in range(len(tips)):
    calcul = tips.loc[i ,'tip'] / tips.loc[i, 'total_bill']
    print(calcul)
ratio.append(calcul)


#len(tips)== len(calcul)

#df['ratio'] = ratio     #여기 오류난다 (칼럼 길이 불일치)

ratio = pd.DataFrame(ratio)     #이렇게 하면 열에 들어가느냐? 몰루 이게 무슨 작업이지 데프화 아닌가 알아냈다!!!(데프화 맞어!!)

result = pd.concat([tips,ratio],axis = 1) #ratio 열 생성

result

0.05944673337257211
0.16054158607350097
0.16658733936220846
0.1397804054054054
0.14680764538430255
0.18623962040332148
0.22805017103762829
0.11607142857142858
0.13031914893617022
0.2185385656292287
0.1665043816942551
0.14180374361883155
0.10181582360570687
0.16277807921866522
0.20364126770060686
0.18164967562557924
0.1616650532429816
0.22774708410067526
0.20624631703005306
0.16222760290556903
0.22767857142857142
0.13553474618038444
0.14140773620798985
0.19228817858954844
0.16044399596367306
0.13138686131386862
0.14958863126402394
0.15760441292356187
0.19815668202764977
0.15267175572519084
0.1518324607329843
0.13623978201634876
0.199203187250996
0.11841469308844853
0.1839145106861642
0.14962593516209477
0.12262415695892091
0.1813349084465446
0.12359550561797752
0.1598976654940838
0.13965087281795513
0.14547537227949597
0.21951219512195122
0.13636363636363638
0.18421052631578946
0.16402405686167304
0.22492127755285649
0.1851851851851852
0.07180385288966724
0.16629711751662973
0.19936204146730463
0.2526724975704568
0.14938236139040506
0.15694164989939638
0.1697965571205008
0.18009235505387378
0.07892659826361484
0.05679666792881484
0.15658362989323843
0.13942407292314066
0.1582060128141942
0.1448225923244026
0.17967332123411978
0.20557681793329688
0.15008527572484368
0.15687250996015936
0.1501519756838906
0.32573289902280134
0.09935739001482945
0.13924050632911392
0.1638935108153078
0.1757469244288225
0.11690245718540582
0.19778481012658228
0.14935505770536323
0.11893434823977164
0.171875
0.14705882352941177
0.13181019332161686
0.156737998843262
0.15432098765432098
0.20408163265306123
0.1817279046673287
0.15299877600979192
0.12703379224030037
0.14843525696238874
0.15349194167306218
0.2188183807439825
0.23674625657628487
0.14177693761814744
0.10355540214014498
0.15562472209871056
0.17391304347826086
0.26348039215686275
0.14285714285714285
0.1177495643515061
0.14662756598240467
0.12468827930174564
0.1427891480247501
0.1203852327447833
0.22026431718061676
0.19505851755526657
0.05643340857787811
0.15521855486173058
0.1950286806883365
0.10677083333333333
0.19814543679843827
0.1701705672352241
0.20614035087719298
0.2795248078266946
0.21428571428571427
0.13793103448275862
0.10506960861570791
0.10647181628392484
0.15558148580318942
0.20219526285384173
0.1693952555963916
0.14084507042253522
0.14481094127111827
0.1212624584717608
0.19760479041916168
0.12518628912071533
0.1753155680224404
0.12539184952978058
0.20192307692307693
0.14093959731543623
0.17370892018779344
0.13774104683195593
0.17574692442882248
0.09553023663453111
0.07861635220125787
0.13961519486926494
0.13428827215756492
0.1631321370309951
0.17798466593647316
0.14688601645123384
0.1936108422071636
0.1413427561837456
0.125
0.20896656534954408
0.20034344590726963
0.19533527696793004
0.12138868657441128
0.18484288354898337
0.1399878271454656
0.17964071856287425
0.07296137339055794
0.13732097725358045
0.1768916155419223
0.2663115845539281
0.17768301350390903
0.15232292460015232
0.15874855156431053
0.0814663951120163
0.10116337885685382
0.1721943048576214
0.10379904504878555
0.15
0.19492158327109782
0.12128562765312312
0.16279069767441862
0.19747235387045814
0.12338062924120913
0.1448225923244026
0.17133066818960593
0.14192495921696574
0.10789980732177264
0.14191106906338694
0.15203021718602455
0.18814675446848542
0.19681165124975397
0.19987349778621127
0.710344827586207
0.09984301412872841
0.23781212841854935
0.0945288753799392
0.11179429849077696
0.13812154696132597
0.4166666666666667
0.102512272596015
0.10620490620490622
0.2421774539219889
0.07717750826901874
0.2805351747949935
0.07398273736128237
0.2416626389560174
0.1674641148325359
0.06565988181221273
0.1928374655647383
0.17316017316017315
0.09560229445506692
0.21150933871781932
0.090014064697609
0.13049095607235142
0.24125452352231608
0.19047619047619047
0.19342359767891684
0.1159823706796567
0.15384615384615385
0.14803849000740193
0.2137894174238375
0.15777080062794346
0.15384615384615385
0.15243902439024393
0.1948368241597662
0.19611414693381907
0.1282437006393381
0.0774593338497289
0.08364235681911825
0.17476489028213166
0.06653359946773121
0.1993047508690614
0.186219739292365
0.18839487565938207
0.23074192403265883
0.08527131782945736
0.10657193605683837
0.12942191544434858
0.18604651162790697
0.10252156602521566
0.18092105263157895
0.2593144560357675
0.22377622377622378
0.18773466833541927
0.11773472429210134
0.15365703749231716
0.19821605550049554
0.1466992665036675
0.20481927710843376
0.13019891500904157
0.08329862557267805
0.19120458891013384
0.29198966408268734
0.13649025069637882
0.19317450096587252
0.12413108242303872
0.07936507936507936
0.03563813585135547
0.13033770583310075
0.2039269720978298
0.07358351729212656
0.08822232024702249
0.09820426487093153
0.1597444089456869

     total_bill   tip sex smoker   day    time  size     ratio  type         0
0         16.99  1.01   여     No   Sun  Dinner     2  0.059447     -  0.159744
1         10.34  1.66   남     No   Sun  Dinner     3  0.160542     -       NaN
2         21.01  3.50   남     No   Sun  Dinner     3  0.166587     -       NaN
3         23.68  3.31   남     No   Sun  Dinner     2  0.139780     -       NaN
4         24.59  3.61   여     No   Sun  Dinner     4  0.146808  단체손님       NaN
..          ...   ...  ..    ...   ...     ...   ...       ...   ...       ...
239       29.03  5.92   남     No   Sat  Dinner     3  0.203927     -       NaN
240       27.18  2.00   여    Yes   Sat  Dinner     2  0.073584     -       NaN
241       22.67  2.00   남    Yes   Sat  Dinner     2  0.088222     -       NaN
242       17.82  1.75   남     No   Sat  Dinner     2  0.098204     -       NaN
243       18.78  3.00   여     No  Thur  Dinner     2  0.159744     -       NaN

[244 rows x 10 columns]

In [ ]:
#2. '성별'이 'Male'인 경우, '남, 'Female'인 경우 '여'로 적용.

#함수를 써봅니다

def change(sex):
    if 'sex' == 'Male':
        변경: 'Male' -> '남'
    else:
        변경: 'Female' -> '여'


change? replace?
#아닌가?? df.loc 써야하나??

In [ ]:
#3. size가 4 이상인 경우 '단체 손님, 이하인 경우 '-'을 적용해 tips['type']열에 넣어주기

#반복되는 분류, 새로운 열을 적용할 것

#반복 분류는 함수를 사용할까 for문을 사용할까 왜 헷갈리는가....................

type = []

for i in range(len(tips)):
    if 'size'>=4:
        print('단체손님')
    else:
        print('-')

        #if 결과들을 받으삼
    type.append()#(if 결과들)

#새로운 열에 적용

df['type'] = type