In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



                                    #훈련 데이터 쪼갬 -> train / test
from sklearn.model_selection import train_test_split
                                    #정확도 계산
from sklearn.metrics import accuracy_score


                                    #둘 다 train/test 데이터 셋에 +a
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score


                #데이터 셋 (아래 둘) 가져오삼
from sklearn.datasets import load_diabetes
from sklearn.datasets import load_wine

holdout

보통 :train - test
훈련데이터가 여유로울 경우: train - vaild - test

# 1. 데이터셋 로드

In [ ]:
data = load_wine()

#data 데프로 변환

X = pd.DataFrame(data.data, columns = data.feature_names)

Y = pd.DataFrame(data.target, columns = ['target'])

In [ ]:
df = pd.concat([X,Y], axis = 1)
df.head()

   alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  target
0    14.23        1.71  2.43  ...                          3.92   1065.0       0
1    13.20        1.78  2.14  ...                          3.40   1050.0       0
2    13.16        2.36  2.67  ...                          3.17   1185.0       0
3    14.37        1.95  2.50  ...                          3.45   1480.0       0
4    13.24        2.59  2.87  ...                          2.93    735.0       0

[5 rows x 14 columns]

In [ ]:
len(X.columns)

13

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  target                        178 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.6 KB

In [ ]:
#계층적 K-Fold: K개로 X 데이터를 나누되, 폴드 안에 들어가는 0,1,2 클래스의 비율을 반영해(원 데이터셋의 비율 유지) 나눠줌

####1. 홀드 아웃 (train-test 쪼개기)

In [ ]:
#train_test_split(X특징, Y정답, test-size=비율, random state = 랜덤 숫자 )

#test-size=비율은 데이터 양에 따라 충분하면 7:3, 적으면 8:2~9:1, 95:5도 가능

#random state: 랜덤으로 데이터셋을 train-test로 분리
#x,y 그리고 train-test 이 받는 순서는 늘 고정 시키시오(변수명은 상관 없음)
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2 , random_state = 42)

In [ ]:
print(f'train 개수 {len(x_train)}, test 개수 {len(x_test)}')

train 개수 142, test 개수 36

In [ ]:
x_train         #확인: 왼쪽 인덱스 숫자를 보면 랜덤. 즉, 랜덤으로 뽑힌 train

     alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
158    14.34        1.68  2.70  ...  0.57                          1.96    660.0
137    12.53        5.51  2.64  ...  0.82                          1.69    515.0
98     12.37        1.07  2.10  ...  1.04                          2.77    660.0
159    13.48        1.67  2.64  ...  0.57                          1.78    620.0
38     13.07        1.50  2.10  ...  1.18                          2.69   1020.0
..       ...         ...   ...  ...   ...                           ...      ...
71     13.86        1.51  2.67  ...  1.36                          3.16    410.0
106    12.25        1.73  2.12  ...  1.00                          3.17    510.0
14     14.38        1.87  2.38  ...  1.20                          3.00   1547.0
92     12.69        1.53  2.26  ...  0.96                          2.06    495.0
102    12.34        2.45  2.46  ...  0.80                          3.38    438.0

[142 rows x 13 columns]

In [ ]:
#가우시안 나이브베이즈 적용

from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()

nb.fit(x_train, y_train)            #특징 연습용, 정답 연습용으로 훈련

nb_predict = nb.predict(x_test)     #문제지만 제공하는 꼴 = 시험. 문제로 낸 x 테스트를 준 것.
accuracy_score(y_test, nb_predict)  #y_test는 x_test의 답

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

1.0

In [ ]:
#선호 분류기로 홀드아웃 적용한 생성-훈련-예측-성능평가 써보기

#홀드아웃 적용
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state = 42)

#분류기: 의사결정나무 적용
from sklearn.tree import DecisionTreeClassifier

#정의
dt = DecisionTreeClassifier()

#훈련
dt.fit(x_train, y_train)

#예측
dt_predict = dt.predict(x_test)

#평가
accuracy_score(y_test, dt_predict)

0.9444444444444444

In [ ]:
#홀드아웃 적용
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state = 42)

#분류기: 의사결정나무 적용
from sklearn.ensemble import RandomForestClassifier

#정의
rf = RandomForestClassifier()

#훈련
rf.fit(x_train, y_train)

#예측
rf_predict = rf.predict(x_test)

#평가
accuracy_score(y_test, rf_predict)

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

1.0

##### KFold 교차검증

- stratifiedKFold
- crossval -> Kfold해서 훈련시킨 모델의 검증(평균으로)

In [ ]:
X

     alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0      14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2      13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3      14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
..       ...         ...   ...  ...   ...                           ...      ...
173    13.71        5.65  2.45  ...  0.64                          1.74    740.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
175    13.27        4.28  2.26  ...  0.59                          1.56    835.0
176    13.17        2.59  2.37  ...  0.60                          1.62    840.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0

[178 rows x 13 columns]

In [ ]:
#선 폴딩 셋팅
#계층별 K폴드 교차 검증
#n_splits= K
#shuffle= 폴드 나눌때 데이터 섞어서 나눌까예?
skf = StratifiedKFold(n_splits=4, shuffle=True)

from sklearn.svm import SVC
svc = SVC()


#cross_val_score(): K(여기선 4) 폴드로 나뉜 데이터를 훈련 시킨 뒤, 평균 성능을 내줘.
svc_result = cross_val_score(estimator = svc,       #모델 알고리즘 넣는 곳 (이 방법으로~)
                X = X,                              #옵션 제목 중 X만 대문자. y는 소문자
                y = Y,                              #애초에 KFold 자체가 데이터를 나누기에 미리 쪼개지 않은 원본, X,Y를 줘도 알아서 해줌
                cv = skf)                           #cv에는 (계층적) k폴드 객체 넣음. 앞에서 말한 skf. Kfold 방식으로 알아서 쪼개시요

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
print(f'정확도: {svc_result.mean():.2f}')       #:.2f => ~의 결과의 소수 둘째자리까지 소수형으로 표현해주삼

정확도: 0.66

In [ ]:
#1. kfold 교차검증 코드 이용해서 10 폴드로 나눈 훈련 수행하기
#알고리즘은 로지스틱 회귀 사용
#성능 평균까지 도출하시예

# 만약 완전 처음이면(홀드아웃 적용 안된 상태) 홀드아웃부터 적용하는건가?: 맞긴함 skf를 안 할거면 홀드아웃을 적용해주고 해당하는 값을 넣어주면 됨

#알고리즘 적용
from sklearn.linear_model import LogisticRegression
#객체 정의
lr = LogisticRegression()

skf = StratifiedKFold (n_splits = 10, shuffle = True)

lr_result = cross_val_score(estimator = lr, X=X, y=Y, cv = skf)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
print(f'정확도: {lr_result.mean():.2f}')
print(f'정확도: {lr_result.min():.2f}')
print(f'정확도: {lr_result.max():.2f}')

정확도: 0.94
정확도: 0.83
정확도: 1.00